/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpeakersRouteImport } from './routes/speakers'
import { Route as HeadphonesRouteImport } from './routes/headphones'
import { Route as EarphonesRouteImport } from './routes/earphones'
import { Route as IndexRouteImport } from './routes/index'

const SpeakersRoute = SpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => rootRouteImport,
} as any)
const HeadphonesRoute = HeadphonesRouteImport.update({
  id: '/headphones',
  path: '/headphones',
  getParentRoute: () => rootRouteImport,
} as any)
const EarphonesRoute = EarphonesRouteImport.update({
  id: '/earphones',
  path: '/earphones',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/earphones': typeof EarphonesRoute
  '/headphones': typeof HeadphonesRoute
  '/speakers': typeof SpeakersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/earphones': typeof EarphonesRoute
  '/headphones': typeof HeadphonesRoute
  '/speakers': typeof SpeakersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/earphones': typeof EarphonesRoute
  '/headphones': typeof HeadphonesRoute
  '/speakers': typeof SpeakersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/earphones' | '/headphones' | '/speakers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/earphones' | '/headphones' | '/speakers'
  id: '__root__' | '/' | '/earphones' | '/headphones' | '/speakers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EarphonesRoute: typeof EarphonesRoute
  HeadphonesRoute: typeof HeadphonesRoute
  SpeakersRoute: typeof SpeakersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/speakers': {
      id: '/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof SpeakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/headphones': {
      id: '/headphones'
      path: '/headphones'
      fullPath: '/headphones'
      preLoaderRoute: typeof HeadphonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earphones': {
      id: '/earphones'
      path: '/earphones'
      fullPath: '/earphones'
      preLoaderRoute: typeof EarphonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EarphonesRoute: EarphonesRoute,
  HeadphonesRoute: HeadphonesRoute,
  SpeakersRoute: SpeakersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
