/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoryRouteImport } from './routes/$category'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryProductSlugRouteImport } from './routes/$category.$productSlug'

const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryProductSlugRoute = CategoryProductSlugRouteImport.update({
  id: '/$productSlug',
  path: '/$productSlug',
  getParentRoute: () => CategoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/$category/$productSlug': typeof CategoryProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/$category/$productSlug': typeof CategoryProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/$category/$productSlug': typeof CategoryProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$category' | '/checkout' | '/$category/$productSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$category' | '/checkout' | '/$category/$productSlug'
  id: '__root__' | '/' | '/$category' | '/checkout' | '/$category/$productSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryRoute: typeof CategoryRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category': {
      id: '/$category'
      path: '/$category'
      fullPath: '/$category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/$productSlug': {
      id: '/$category/$productSlug'
      path: '/$productSlug'
      fullPath: '/$category/$productSlug'
      preLoaderRoute: typeof CategoryProductSlugRouteImport
      parentRoute: typeof CategoryRoute
    }
  }
}

interface CategoryRouteChildren {
  CategoryProductSlugRoute: typeof CategoryProductSlugRoute
}

const CategoryRouteChildren: CategoryRouteChildren = {
  CategoryProductSlugRoute: CategoryProductSlugRoute,
}

const CategoryRouteWithChildren = CategoryRoute._addFileChildren(
  CategoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryRoute: CategoryRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
